{% set version = "2.0.0" %}
{% set hash = "4a73a77053822ca1ed6d4a2af416d31028ec992fb0ffa794af95bd6216bb6a20" %}
{% set build_number = "0" %}

package:
  name: termcolor-cpp
  version: {{ version }}

source:
  url: https://github.com/ikalnytskyi/termcolor/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  commands:
    - test -e $PREFIX/include/termcolor/termcolor.hpp  # [not win]
    - if not exist %PREFIX%\Library\include\termcolor\termcolor.hpp exit 1  # [win]

about:
  home: https://github.com/ikalnytskyi/termcolor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Header-only C++ library for printing colored messages to the terminal.'
  dev_url: https://github.com/ikalnytskyi/termcolor
  doc_url: https://github.com/ikalnytskyi/termcolor#how-to-use
  doc_src_url: https://github.com/ikalnytskyi/termcolor

extra:
  recipe-maintainers:
    - adriendelsalle
